const { Button: SButton, IconButton: SIconButton, Icon: SIcon, Input: SInput, Select: SSelect, Checkbox: SCheckbox, Switch: SSwitch, Badge: SBadge, Tag: STag, Card: SCard, Tabs: STabs } = window.RejuveluxeDesignSystem_0fe2c7;
function Block({ label, note, children }) { return <div className="spec-block"><div className="stack g2"><Eyebrow>{label}</Eyebrow>{note && <p className="cap">{note}</p>}</div><div className="stack g6">{children}</div></div>; }
function Specimen({ theme }) {
  const cols = [['--bg-page', 'Page'], ['--surface-card', 'Surface'], ['--bg-page-alt', 'Inset'], ['--text-primary', 'Ink'], ['--text-secondary', 'Ink 2'], ['--text-tertiary', 'Muted'], ['--border-subtle', 'Line'], ['--border-strong', 'Line strong'], ['--accent', 'Gold']];
  return <div className="theme-pane" data-theme={theme}>
    <div className="between"><Eyebrow>{theme} theme</Eyebrow><span className="cap">Tokens redefined on [data-theme]</span></div>
    <div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fill,minmax(96px,1fr))', gap: 12 }}>{cols.map(([t, l]) => <div key={t} className="sw"><i style={{ background: `var(${t})` }} /><span>{l}<br />{t}</span></div>)}</div>
    <div className="grid" style={{ gridTemplateColumns: 'repeat(5,1fr)', gap: 12 }}>{PRODUCTS.map((p) => <div key={p.id} className="sw"><i style={{ background: p.tin, boxShadow: `inset 0 -16px 0 ${p.ink}` }} /><span>{p.name}<br />tin / ink</span></div>)}</div>
    <div className="stack g4 rule-t" style={{ paddingTop: 24 }}>
      <p className="display" style={{ fontSize: 'clamp(36px,6cqw,64px)' }}>Earned, <em>not</em> indulged.</p><span className="cap">Display · Playfair Display 400 · italic for emphasis</span>
      <h2 className="h1">Five expressions. One garden.</h2><span className="cap">H1 · Playfair Display 400 · balanced</span>
      <h3 className="h3 it">Golden Tips</h3><span className="cap">H3 italic · product names</span>
      <p className="lead">India doesn't need better tea. India needs better access to its best tea.</p><span className="cap">Lead · Figtree 300 18/1.65 · editorial</span>
      <p className="body">Made almost entirely from young, tender buds, minimally processed to preserve every delicate note.</p><span className="cap">Body · Figtree 400 15/1.5</span>
      <Eyebrow>Evidence · Lot [LOT-0000]</Eyebrow><span className="cap">Eyebrow · Figtree 500 11 · 0.22em caps · gold</span>
      <span className="price">₹1,250 · 0.80 g</span><span className="cap">Price and data · Playfair 18 · tabular numerals</span>
    </div>
    <div className="row g4" style={{ flexWrap: 'wrap' }}><SButton>Primary</SButton><SButton variant="outline">Outline</SButton><SButton variant="ghost">Ghost</SButton><SInput placeholder="Input" size="sm" style={{ width: 160 }} /></div>
  </div>;
}
function SpecsPage({ onAdd, openCart, setItems, toast }) {
  const [state, setState] = React.useState('golden');
  const [sw, setSw] = React.useState(false);
  return <main data-screen-label="Component sheet and specimen"><div className="wrap sec spec">
    <div className="stack g4"><Eyebrow>Deliverables 4, 5, 8, 9, 10</Eyebrow><h1 className="display" style={{ fontSize: 'clamp(40px,4.6cqw,64px)' }}>Components and specimen.</h1><p className="lead">Every object on this page is the live component used in the pages, not a drawing of it.</p></div>
    <Block label="10 · Wordmark" note="Cinzel substitute for the Trajan-style small caps. Strapline in eyebrow style. One colour. No crest until the client supplies an SVG."><div className="grid cols-2">{['light', 'dark'].map((t) => <div key={t} className="theme-pane" data-theme={t} style={{ gap: 40, alignItems: 'flex-start' }}><Wordmark size={28} /><Wordmark stacked size={34} /><span className="cap">{t} · horizontal, stacked</span></div>)}</div></Block>
    <Block label="9 · Colour and type" note="Both themes side by side. Dark redefines semantic tokens only; base palette is unchanged."><div className="grid cols-2" style={{ alignItems: 'start' }}><Specimen theme="light" /><Specimen theme="dark" /></div></Block>
    <Block label="4 · Collection ladder" note="Three states. Rest, active stop (hover, focus or touch), and narrow viewport where the track scrolls inside its own container.">
      <div className="stack g3"><Eyebrow muted>At rest</Eyebrow><div className="hair" style={{ padding: 24 }}><Ladder /></div></div>
      <div className="stack g3"><div className="between"><Eyebrow muted>Active stop · {byId(state).name}</Eyebrow><STabs variant="underline" items={PRODUCTS.map((p) => ({ value: p.id, label: p.name }))} value={state} onChange={setState} /></div><div className="hair" style={{ padding: 24 }}><Ladder active={state} onSelect={setState} onOpen={(p) => toast({ title: p.name, description: 'Opens the product page.' })} /></div></div>
      <div className="stack g3"><Eyebrow muted>Narrow · 390 px · horizontal scroll, snap per stop</Eyebrow><div className="hair rjx-app" style={{ width: 390, padding: 16, containerType: 'inline-size', background: 'var(--bg-page)' }}><Ladder compact /></div></div>
    </Block>
    <Block label="5 · Cart drawer" note="Empty and filled states open the real drawer. Free-shipping progress in ink on inset surface, 4 px. Focus is trapped while open; Escape closes."><div className="row g3" style={{ flexWrap: 'wrap' }}><SButton variant="outline" onClick={() => { setItems([]); openCart(); }}>Open empty</SButton><SButton onClick={() => { setItems([{ id: 'golden', qty: 1 }, { id: 'ctc', qty: 2 }]); openCart(); }}>Open filled</SButton></div></Block>
    <Block label="8 · Buttons" note="Ink primary, hairline outline that fills on hover, ghost that goes gold. Three sizes. 2 px radius. No shadow, no transform."><div className="row g3" style={{ flexWrap: 'wrap' }}><SButton size="lg">Add to cart</SButton><SButton>Add to cart</SButton><SButton size="sm">Add</SButton><SButton variant="outline">Details</SButton><SButton variant="ghost" iconRight={<SIcon name="arrow-right" size={14} />}>Brew guide</SButton><SButton disabled>Sold out</SButton><SIconButton label="Cart" badge={3}><SIcon name="shopping-bag" size={20} /></SIconButton></div></Block>
    <Block label="8 · Inputs" note="1 px border, 2 px radius, gold focus ring. Eyebrow label above."><div className="grid cols-3"><SInput label="Email" placeholder="name@domain.in" /><SInput label="Pincode" placeholder="000000" hint="Six digits" /><SInput label="Voucher" error="Code not recognised" defaultValue="ASSAM10" /><SSelect label="Size" options={[{ value: '50', label: '50 g' }, { value: '100', label: '100 g' }]} defaultValue="50" /><div className="stack g3" style={{ paddingTop: 22 }}><SCheckbox label="Gift wrap" /><SSwitch label="Subscribe and save" checked={sw} onChange={setSw} /></div></div></Block>
    <Block label="8 · Evidence rows and labels" note="The core repeating object. Eyebrow label left, tabular value right, hairline between rows. Bracketed slots are visibly empty."><div className="grid cols-2"><Evidence rows={[['Garden', SLOT.estate], ['District', SLOT.district], ['Elevation', SLOT.elevation], ['Grade', SLOT.grade], ['Flush', SLOT.flush], ['Pluck month', SLOT.pluck], ['Lot', SLOT.lot], ['Net weight', '100 g']]} /><div className="stack g6"><div className="stack g2"><Eyebrow>Gold eyebrow · section label</Eyebrow><Eyebrow muted>Muted eyebrow · field label</Eyebrow></div><div className="row g3" style={{ flexWrap: 'wrap' }}><SBadge>Neutral</SBadge><SBadge tone="ink">Rare</SBadge><SBadge tone="gold">New</SBadge><STag>Whole leaf</STag><STag>Second flush</STag></div></div></div></Block>
    <Block label="8 · Swatches and intensity scales" note="24 px tin colour with a 1 px ring in the tin's ink. Scales fill in the ink colour, five segments, labelled Body and Briskness."><div className="grid cols-5" style={{ gridTemplateColumns: 'repeat(5,1fr)' }}>{PRODUCTS.map((p) => <div key={p.id} className="stack g3"><div className="row g3"><Swatch p={p} /><span className="small" style={{ color: 'var(--text-primary)' }}>{p.name}</span></div><div className="stack g3" style={{ color: p.ink }}><Scale label="Body" value={p.body} /><Scale label="Briskness" value={p.brisk} /></div></div>)}</div></Block>
    <Block label="8 · Product tile" note="The only card on the site. Tin on its colour, name, italic descriptor, evidence rows, price, both CTAs. Ink colour as a 3 px top rule."><div className="grid cols-3">{PRODUCTS.slice(0, 3).map((p) => <Tile key={p.id} p={p} onAdd={onAdd} onOpen={(x) => toast({ title: x.name, description: 'Opens the product page.' })} />)}</div></Block>
    <Block label="8 · Accordion" note="Full-width row, hairline bottom, plus/minus, closed by default, 200 ms height ease."><div style={{ maxWidth: 640 }}><Accordion items={FAQS.slice(0, 3)} /></div></Block>
    <Block label="8 · Greybox" note="Photography placeholder at the correct ratio, labelled with the asset direction. Never stock imagery."><div className="grid cols-3"><Greybox label="Product · seamless surface" ratio="4 / 5" /><Greybox label="Editorial · 3:2" ratio="3 / 2" /><Greybox label="Garden · 16:9" ratio="16 / 9" /></div></Block>
  </div></main>;
}
Object.assign(window, { SpecsPage });
